## Server Properties
server:
    port: 8080
    compression:
        enabled: true
spring:
    jackson:
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
        time-zone: UTC
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1
        username: sa
        password:
        platform: hsqldb  
    mail:
        default-encoding: UTF-8
        host: smtp.gmail.com
        port: 587
        username: carloantonioj@gmail.com
        password: rofkziwrzetueily
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        protocol: smtp
        test-connection: false

security:
    jwt:
        secret: JWTSuperSecretKey
        expiration: 604800000

## App Properties
    

## Spring Profiles
# spring.profiles.active=prod
